steps:
  # Build the container image with both :latest and :$COMMIT_SHA tags
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/zwickfi/zwickfi-monarch:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/zwickfi/zwickfi-monarch:latest'
      - '.'

  # Push both tags in a single step
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/zwickfi/zwickfi-monarch'

  # Deploy container image to Cloud Run using the :latest tag
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'zwickfi'
      - '--image'
      - 'gcr.io/zwickfi/zwickfi-monarch:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/zwickfi/zwickfi-monarch:$COMMIT_SHA'
  - 'gcr.io/zwickfi/zwickfi-monarch:latest'
