steps:
  # Build the container image with both :latest and :$COMMIT_SHA tags
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/zwickfi/zwickfi-monarch:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/zwickfi/zwickfi-monarch:latest'
      - '.'

  # Push both tags in a single step
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/zwickfi/zwickfi-monarch'

  # Deploy the container as a Cloud Run Job instead of a service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'deploy'
      - 'zwickfi-monarch'  # Match YAML job name
      - '--image'
      - 'gcr.io/zwickfi/zwickfi-monarch:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--task-timeout=600s'
      - '--max-retries=3'
      - '--cpu=4'
      - '--memory=2Gi'
      - '--set-env-vars=GOOGLE_APPLICATION_CREDENTIALS=/secrets/service_account.json'
      - '--set-secrets=MONARCH_EMAIL=MONARCH_EMAIL:latest'
      - '--set-secrets=MONARCH_PASSWORD=MONARCH_PASSWORD:latest'
      - '--set-secrets=MONARCH_SECRET_KEY=MONARCH_SECRET_KEY:latest'
      - '--set-secrets=/secrets/service_account.json=service-account-monarch:latest'
      - '--service-account=zwickfi-app@zwickfi.iam.gserviceaccount.com'

images:
  - 'gcr.io/zwickfi/zwickfi-monarch:$COMMIT_SHA'
  - 'gcr.io/zwickfi/zwickfi-monarch:latest'